export default {
  "login": "sudarshan604",
  "id": 57833720,
  "node_id": "MDQ6VXNlcjU3ODMzNzIw",
  "avatar_url": "https://avatars.githubusercontent.com/u/57833720?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/sudarshan604",
  "html_url": "https://github.com/sudarshan604",
  "followers_url": "https://api.github.com/users/sudarshan604/followers",
  "following_url": "https://api.github.com/users/sudarshan604/following{/other_user}",
  "gists_url": "https://api.github.com/users/sudarshan604/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/sudarshan604/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/sudarshan604/subscriptions",
  "organizations_url": "https://api.github.com/users/sudarshan604/orgs",
  "repos_url": "https://api.github.com/users/sudarshan604/repos",
  "events_url": "https://api.github.com/users/sudarshan604/events{/privacy}",
  "received_events_url": "https://api.github.com/users/sudarshan604/received_events",
  "type": "User",
  "site_admin": false,
  "name": "sudarshan kshetri",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 19,
  "public_gists": 0,
  "followers": 9,
  "following": 11,
  "created_at": "2019-11-16T12:32:01Z",
  "updated_at": "2022-12-19T07:47:15Z"
}