// 20221222002101
// https://api.github.com/users/Bibekdhkl

export default{
  "login": "Bibekdhkl",
  "id": 48583944,
  "node_id": "MDQ6VXNlcjQ4NTgzOTQ0",
  "avatar_url": "https://avatars.githubusercontent.com/u/48583944?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Bibekdhkl",
  "html_url": "https://github.com/Bibekdhkl",
  "followers_url": "https://api.github.com/users/Bibekdhkl/followers",
  "following_url": "https://api.github.com/users/Bibekdhkl/following{/other_user}",
  "gists_url": "https://api.github.com/users/Bibekdhkl/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Bibekdhkl/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Bibekdhkl/subscriptions",
  "organizations_url": "https://api.github.com/users/Bibekdhkl/orgs",
  "repos_url": "https://api.github.com/users/Bibekdhkl/repos",
  "events_url": "https://api.github.com/users/Bibekdhkl/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Bibekdhkl/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Bibek Dhakal",
  "company": null,
  "blog": "https://bibekdhkl.github.io",
  "location": "Nepal",
  "email": null,
  "hireable": null,
  "bio": "Learning to Code",
  "twitter_username": "bibekdhkl",
  "public_repos": 35,
  "public_gists": 4,
  "followers": 73,
  "following": 68,
  "created_at": "2019-03-15T08:03:19Z",
  "updated_at": "2022-12-05T19:06:30Z"
}