import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/Banner'
import Image from 'next/image'
import Card from '@/components/Card'
import CoffeeStoreData from '../data/coffee-store.json'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  console.log('get static props')
return{ 
    props: { 
     CoffeeStore:CoffeeStoreData
   } 
};
};


export default function Home(props) {

const handleClick=()=>{
  console.log('click')
}

return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
 
 <main className={styles.main}>

          <Banner buttontext="View store nearby" handleClick={handleClick} /> 
        <div className={styles.heroImage}>
            <Image src="/static/hero-img.jpg" width={300} height={300}/>
        </div>
        {props.CoffeeStore.length>0 &&
        <>
          <h2 className={styles.heading2}>Toronto coffee store</h2>
            <div className={styles.cardLayout}>
                {props.CoffeeStore.map(CoffeeStore=>{
                   return (
                    <Card 
                    key={CoffeeStore.id}
                    name={CoffeeStore.name} 
                    img={CoffeeStore.imgUrl}
                    href={`coffee-store/${CoffeeStore.id}`}  
                    className={styles.card}
                    />
                   )
                })}
              </div>
          </>}  
                 
 </main>


</>
  )
}
