export const PRODUCT_BEGIN="productbegin"
export const PRODUCT_SUCCESS="productsuccess"
export const PRODUCT_Fail="productFail"
export const SINGLE_PRODUCT_BEGIN="singleproductbrgin"
export const SINGLE_LOAD="single_load"